language: ruby
rvm:
- 2.0.0
script:
- psql -c 'create database ivan_terrible_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
bundler_args: --binstubs=./bundler_stubs
deploy:
  provider: heroku
  api_key:
    secure: dJorqYFF62fkQHnqQrU/tWRhdzBB3Zji4QGEhtln1ddAQL/k/hi1u/k18MtLYOdXm926DewAGb4iER5495C426vNBsIVqKR9z9vdecqnJAZqD3pIWpmLE1H03yqhZcXKRXT3HvX+3G0woKSi9RGQGj5CgOohjBQMH81fj7rgwWY=
  app: nbarnes
  on:
    repo: nbarnes/ivan-the-terribles-blog
